### PR TITLE
Fix rv32e tests generation

### PR DESCRIPTION
**Pull request by bilalsakhawat-10xe**
Fixed the issue #8 .

### CODE REVIEW

**Comment by pawks** [comment]
The tests have to follow the [test format spec](https://github.com/riscv/riscv-arch-test/blob/master/spec/TestFormatSpec.adoc) and hence the name of the macro cannot be changed. Hence it would be a better solution to put the register initialisations for registers 16-31 in a `ifndef - endif` block with a custom macro name ```RVTEST_E``` and add the following line in the config node for the cgfs:
```
def RVTEST_E = True
```

**Comment by bilalsakhawat-10xe** [comment]
Sure I'll make changes and push the commit.

**Comment by bilalsakhawat-10xe** [comment]
@pawks I made the suggested changes.

**Comment by bilalsakhawat-10xe** [comment]
@pawks this PR waiting for approval.

**Comment by pawks** [comment]
This PR can be merged.

**Pull request merged**
